import type { Theme, ThemeConfig } from '../types';

export const THEMES: Record<Theme, ThemeConfig> = {
  'code-vibes': {
    name: 'code-vibes',
    label: 'Code vibes theme',
    previewImage: '/images/cards/code-vibes/preview.png',
    cardImages: [
      '/images/cards/code-vibes/card-01.png',
      '/images/cards/code-vibes/card-02.png',
      '/images/cards/code-vibes/card-03.png',
      '/images/cards/code-vibes/card-04.png',
      '/images/cards/code-vibes/card-05.png',
      '/images/cards/code-vibes/card-06.png',
      '/images/cards/code-vibes/card-07.png',
      '/images/cards/code-vibes/card-08.png',
      '/images/cards/code-vibes/card-09.png',
      '/images/cards/code-vibes/card-10.png',
      '/images/cards/code-vibes/card-11.png',
      '/images/cards/code-vibes/card-12.png',
      '/images/cards/code-vibes/card-13.png',
      '/images/cards/code-vibes/card-14.png',
      '/images/cards/code-vibes/card-15.png',
      '/images/cards/code-vibes/card-16.png',
      '/images/cards/code-vibes/card-17.png',
      '/images/cards/code-vibes/card-18.png',
    ],
  },
  gaming: {
    name: 'gaming',
    label: 'Gaming theme',
    previewImage: '/images/cards/gaming/preview.png',
    cardImages: [
      '/images/cards/gaming/card-01.png',
      '/images/cards/gaming/card-02.png',
      '/images/cards/gaming/card-03.png',
      '/images/cards/gaming/card-04.png',
      '/images/cards/gaming/card-05.png',
      '/images/cards/gaming/card-06.png',
      '/images/cards/gaming/card-07.png',
      '/images/cards/gaming/card-08.png',
      '/images/cards/gaming/card-09.png',
      '/images/cards/gaming/card-10.png',
      '/images/cards/gaming/card-11.png',
      '/images/cards/gaming/card-12.png',
      '/images/cards/gaming/card-13.png',
      '/images/cards/gaming/card-14.png',
      '/images/cards/gaming/card-15.png',
      '/images/cards/gaming/card-16.png',
      '/images/cards/gaming/card-17.png',
      '/images/cards/gaming/card-18.png',
    ],
  },
  'da-projects': {
    name: 'da-projects',
    label: 'DA Projects theme',
    previewImage: '/images/cards/da-projects/preview.png',
    cardImages: [
      '/images/cards/da-projects/card-01.png',
      '/images/cards/da-projects/card-02.png',
      '/images/cards/da-projects/card-03.png',
      '/images/cards/da-projects/card-04.png',
      '/images/cards/da-projects/card-05.png',
      '/images/cards/da-projects/card-06.png',
      '/images/cards/da-projects/card-07.png',
      '/images/cards/da-projects/card-08.png',
      '/images/cards/da-projects/card-09.png',
      '/images/cards/da-projects/card-10.png',
      '/images/cards/da-projects/card-11.png',
      '/images/cards/da-projects/card-12.png',
      '/images/cards/da-projects/card-13.png',
      '/images/cards/da-projects/card-14.png',
      '/images/cards/da-projects/card-15.png',
      '/images/cards/da-projects/card-16.png',
      '/images/cards/da-projects/card-17.png',
      '/images/cards/da-projects/card-18.png',
    ],
  },
  foods: {
    name: 'foods',
    label: 'Foods theme',
    previewImage: '/images/cards/foods/preview.png',
    cardImages: [
      '/images/cards/foods/card-01.png',
      '/images/cards/foods/card-02.png',
      '/images/cards/foods/card-03.png',
      '/images/cards/foods/card-04.png',
      '/images/cards/foods/card-05.png',
      '/images/cards/foods/card-06.png',
      '/images/cards/foods/card-07.png',
      '/images/cards/foods/card-08.png',
      '/images/cards/foods/card-09.png',
      '/images/cards/foods/card-10.png',
      '/images/cards/foods/card-11.png',
      '/images/cards/foods/card-12.png',
      '/images/cards/foods/card-13.png',
      '/images/cards/foods/card-14.png',
      '/images/cards/foods/card-15.png',
      '/images/cards/foods/card-16.png',
      '/images/cards/foods/card-17.png',
      '/images/cards/foods/card-18.png',
    ],
  },
};
